quarkus:
  application:
    name: odin-gateway
    version: ${project.version}
  oidc:
    enabled: false
  keycloak:
    policy-enforcer:
      enabled: false
  http:
    port: 0
    test-port: 0
    test-ssl-port: 0
    read-timeout: 30M
    cors:
      enabled: true
      methods: "GET, POST, PUT, PATCH, DELETE, OPTIONS"
      headers: "Content-Type, Authorization, Origin, Referer, User-Agent"
      origins: /.*/
      access-control-allow-credentials: true
  thread-pool:
    core-threads: 10
    keep-alive-time: 1M
  log:
    level: INFO
    category:
      "io.quarkus.vertx.http.runtime.QuarkusErrorHandler":
        level: DEBUG
    console:
      format: "%n %d{yyyy-MM-dd HH:mm:ss.SSS} [%p] [%t] [ %X{user} ] %C : %s%e"
  datasource:
    enabled: false
  swagger-ui:
    always-include: false
  smallrye-openapi:
    info-title: ODIN-SERVICE
    info-version: ${project.version}
    info-description: ODIN gateway service
    info-license-name: Apache 2.0
    info-license-url: https://www.apache.org/licenses/LICENSE-2.0.html
    security-scheme: jwt
    auto-add-security-requirement: false

gateway:
  routes:
    downstream:
      path-prefixes: [ "/api/v1" ]
      strip-prefix: false
      target:
        base-url: ${DOWNSTREAM_BASE_URL:http://localhost:8089}
mp:
  jwt:
    verify:
      publickey:
        location: classpath:keys/publicKey.pem
        issuer: heimdall@repensi.com